### ISSUE TITLE
Flex 很多属性前缀冗余

### ISSUE THREAD

**Issue by yisibl** [ecomfe/est#19]
比如最明显的 ```-moz-flex-wrap``` [属性](https://github.com/ecomfe/est/blob/master/src/compatibility.less#L694)，Firefox并未实现带有前缀版本。

也就是说所有多行相关的属性， Firefox 28 之前均为实现带有前缀版本。

```css
.flex-wrap(@wrap) {
    @ms-wrap: ~`"@{wrap}".replace(/nowrap/ig, "none")`;
    -webkit-flex-wrap: @wrap;
       -moz-flex-wrap: @wrap;
        -ms-flex-wrap: @ms-wrap;
            flex-wrap: @wrap; 
}
```
