### ISSUE TITLE
est-layout-sidebar问题

### ISSUE THREAD

**Issue by hengjia** [ecomfe/est#42]
```
body {
    .est-layout-sidebar(left, 200px, "#main", ".sidebar");
}
```

上面的代码编译结果是：

```
body {
  position: relative;
}
body > "#main" {
  overflow: hidden;
  margin-left: 200px;
}
body > ".sidebar" {
  position: absolute;
  top: 0;
  left: 0;
  width: 200px;
}

```
这样不能用吧，因为编译出来的body的子代选择器带有`""`，应该是没有冒号的。

**Comment by zmmbreeze** [comment]
根据[首页的文档](http://ecomfe.github.io/est/#layout)，正确的用法应该是：

```less
body {
    .est-layout-sidebar(left, 200px, ~"#main", ~".sidebar");
}
```

输出的结果是：

```css
body {
  position: relative;
}
body > #main {
  overflow: hidden;
  margin-left: 200px;
}
body > .sidebar {
  position: absolute;
  top: 0;
  left: 0;
  width: 200px;
}
```
